FROM nginx:latest

# Copy the template config file
COPY nginx.conf.template /etc/nginx/nginx.conf.template

# Copy a startup script
COPY start.sh /start.sh
RUN chmod +x /start.sh


# Expose ports
EXPOSE 8080 8443

CMD ["/start.sh"]
